// generated by Csharpenizer (https://color-of-code.de)
using stdc;

namespace main {
  public partial class Program {

/* fopen example */
// #include <stdio.h>
int main ()
{
  C.FILE pFile;
  pFile = C.fopen ("ex_fopen.txt","w");
  if (pFile!=C.NULL)
  {
    C.fputs ("fopen example",pFile);
    C.fclose (pFile);
  }
  return 0;
}


    static int Main (string[] args) {
      var p = new Program();
      return C.RunIMain (args, p.main);
    }
  }
}
