// generated by Csharpenizer (https://github.com/Color-Of-Code/stdc.NET)
using stdc;

namespace main {
  public partial class Program {

/* strlen example */
// #include <stdio.h>
// #include <string.h>

int main ()
{
  char[] szInput = new char[256];
  C.printf ("Enter a sentence: ");
  C.gets (szInput);
  C.printf ("The sentence entered is %u characters long.\n",C.strlen(szInput));
  return 0;
}


    static int Main (string[] args) {
      var p = new Program();
      return C.RunIMain (args, p.main);
    }
  }
}
