// generated by Csharpenizer (https://color-of-code.de)
using stdc;

namespace main {
  public partial class Program {

/* scanf example */
// #include <stdio.h>

int main ()
{
  char[] str = new char[80];
  int i;

  C.printf ("Enter your family name: ");
  C.scanf ("%s",str);  
  C.printf ("Enter your age: ");
  C.scanf ("%d",out i);
  C.printf ("Mr. %s , %d years old.\n",str,i);
  C.printf ("Enter a hexadecimal number: ");
  C.scanf ("%x",out i);
  C.printf ("You have entered %#x (%d).\n",i,i);
  
  return 0;
}


    static int Main (string[] args) {
      var p = new Program();
      return C.RunIMain (args, p.main);
    }
  }
}
