// generated by Csharpenizer (https://color-of-code.de)
using stdc;

namespace main {
  public partial class Program {

/* qsort example */
// #include <stdio.h>
// #include <stdlib.h>

int[] values = new int[] { 40, 10, 100, 90, 20, 25 };

int compare (object a, object b)
{
  return ( a - b );
}

int main ()
{
  int n;
  C.qsort (values, 6, sizeof(int), compare);
  for (n=0; n<6; n++)
     C.printf ("%d ",values[n]);
  return 0;
}


    static int Main (string[] args) {
      var p = new Program();
      return C.RunIMain (args, p.main);
    }
  }
}
