// generated by Csharpenizer (https://github.com/Color-Of-Code/stdc.NET)
using stdc;

namespace main {
  public partial class Program {

/* srand example */
// #include <stdio.h>
// #include <stdlib.h>
// #include <time.h>

int main ()
{
  C.printf ("First number: %d\n", C.rand() % 100);
  C.srand ( C.time(C.NULL) );
  C.printf ("Random number: %d\n", C.rand() % 100);
  C.srand ( 1 );
  C.printf ("Again the first number: %d\n", C.rand() %100);

  return 0;
}


    static int Main (string[] args) {
      var p = new Program();
      return C.RunIMain (args, p.main);
    }
  }
}
