// generated by Csharpenizer (https://color-of-code.de)
using stdc;

namespace main {
  public partial class Program {

/* strcat example */
// #include <stdio.h>
// #include <string.h>

int main ()
{
  char[] str = new char[80];
  C.strcpy (str,"these ");
  C.strcat (str,"strings ");
  C.strcat (str,"are ");
  C.strcat (str,"concatenated.");
  C.puts (str);
  return 0;
}


    static int Main (string[] args) {
      var p = new Program();
      return C.RunIMain (args, p.main);
    }
  }
}
