// generated by Csharpenizer (https://color-of-code.de)
#region Namespace wrapping
//css_reference stdc.dll;
using stdc;

namespace main {
  public partial class Program {
#endregion

// #include <stdio.h>

int i=1;

void solution(int n,char from,char to,char temp)
{
	if(n>0)
	{
		solution(n-1,from,temp,to);
		C.printf("step %d -> Move the disk %d form %c to %c.\n",i++,n,from,to);
		solution(n-1,temp,to,from);
	}
}

int main()
{
	int n;
	C.printf("Tower of honai problem.\n");
	C.printf("Enter the no. disks:");
	C.scanf("%d",out n);
	C.printf("The solution.\n");
	solution(n,'L','R','C');
	return 0;
}


    #region Main trampoline
    static int Main (string[] args) {
      Program p = new Program();
      return C.RunIMain (args, p.main);
    }
    #endregion
#region Namespace wrapping
  }
}
#endregion
