// generated by Csharpenizer (https://color-of-code.de)
using stdc;

namespace main {
  public partial class Program {

/* fputc example: alphabet writer */
// #include <stdio.h>

int main ()
{
  C.FILE pFile;
  char c;

  pFile = C.fopen ("ex_fputc.txt","w");
  if (pFile!=C.NULL)
  {
    for (c = 'A' ; c <= 'Z' ; c++)
    {
      C.fputc ( (int) c , pFile );
    }
    C.fclose (pFile);
  }
  return 0;
}


    static int Main (string[] args) {
      var p = new Program();
      return C.RunIMain (args, p.main);
    }
  }
}
